# A modified config which pulls pages from every site which Crom tracks.

output-path = "results-all.json"
save-page-offset = "1000"
sites = [
    "scp-wiki",
    "scp-ru",
    "scpko",
    "scp-wiki-cn",
    "fondationscp", # FR
    "scp-pl",
    "lafundacionscp", # ES
    "scp-th",
    "scp-jp",
    "scp-wiki-de",
    "fondazionescp", # IT
    "scp-ukrainian",
    "scp-pt-br",
    "scp-cs",
    "scp-zh-tr",
    "scp-un",
    "scp-el",
    "scp-idn",
    "scp-nd",
    "scpvakfi", # TR
    "scp-vn",
]
