# The location within output/ to store retrieved data.
output-path = "results.json"

# How many pages to download in between saving data to disk.
save-page-offset = "100"

# Which wikidot site(s) to pull data for.
sites = ["scp-wiki"]
